name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # main ë¸Œëœì¹˜ì— í‘¸ì‹œë  ë•Œ ì‘ë™
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # ìµœì‹  ë²„ì „ ì‚¬ìš©
          channel: 'stable'
          
      - run: flutter build web --release --base-href "/travel-wallet-pro-web/"
      
      # ğŸ’¡ [í•µì‹¬ ì¶”ê°€] ì„œì¹˜ ì½˜ì†” ì¸ì¦ íŒŒì¼ì„ ë¹Œë“œ í´ë”ë¡œ ê°•ì œ ë³µì‚¬
      - name: Copy Search Console Verification File
        run: cp web/google0a74ca61ce6611d3.html build/web/
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # ë¹Œë“œëœ ê²°ê³¼ë¬¼ì´ ìˆëŠ” í´ë”
          branch: gh-pages # ë°°í¬ìš© ë¸Œëœì¹˜